# Use the Docker image with Docker installed.
image: docker:latest

# Define services required for Docker.
services:
  - docker:dind

# Define stages in the pipeline
stages:
  - build
  - test
  - deploy

# Define the 'build' stage to build the Docker image
build_image:
  stage: build
  script:
    - docker build -t my-node-app .
  tags:
    - shell

# Define the 'test' stage
run_tests:
  stage: test
  script:
    - docker run --rm my-node-app npm test
  tags:
    - shell

# Define the 'deploy' stage (customize as needed)
deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # Add deployment commands here
  only:
    - main
  tags:
    - shell
